In [10]:
# Block Diagonal Matrix for Skew Symmetric matrix
import numpy as np
import scipy.linalg as la
from scipy.linalg import block_diag

# even size example
X = np.array([[0,-1,5,-3], [1,0,0,-1], [0,0,3,-2], [0,0,5,-3]]) 
# # odd size example
# X=np.array([[0,1,2,3,4], [-1,0,2,3,4], [-2,-2,0,3,4], [-3,-3,-3,0,4], [-4,-4,-4,-4,0]]) 
n = X.shape[0]
##########################################################################################################

# eigenvectors
[u,v] = np.linalg.eig(X)

perm = np.argsort(np.abs(np.imag(u)))
unew = 1j*np.imag(u[perm])
vnew = v[perm,:]

# number of blocks : (Real eigenvalues of X are always 0, and each block-size for complex values = 2 by 2)
numblocks = np.flatnonzero(unew).size // 2
num_zeros = n - (2 * numblocks)

T = la.block_diag(*[1.]*num_zeros, np.kron(1/np.sqrt(2)*np.eye(numblocks), np.array([[1.,1j],[1,-1j]])))
Eigs = np.real(T.conj().T.dot(np.diag(unew).dot(T)))
Evecs = np.real(vnew.dot(T))

# Block diagonal matrix for given matrix
print(Eigs)

[[ 0. -1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]
