In [50]:
import numpy as np
import scipy.linalg as la
import scipy
from scipy.linalg import block_diag

# X=np.array([[0,-1,5,-3], [1,0,0,-1], [0,0,3,-2], [0,0,5,-3]])
X=np.array([[0,1,2,3,4], [-1,0,2,3,4], [-2,-2,0,3,4], [-3,-3,-3,0,4], [-4,-4,-4,-4,0]])
A, B = np.array([[0,-1], [1,0]]), np.array([[3,2],[5,-3]])
M = la.block_diag(A, B)
X

array([[ 0,  1,  2,  3,  4],
       [-1,  0,  2,  3,  4],
       [-2, -2,  0,  3,  4],
       [-3, -3, -3,  0,  4],
       [-4, -4, -4, -4,  0]])

In [15]:
# [u,v] = np.linalg.eig(M)
# print(np.linalg.eig(M))

In [51]:
[u,v] = np.linalg.eig(X)
print(np.linalg.eig(X))

(array([ 0.00000000e+00+9.91364871j,  0.00000000e+00-9.91364871j,
        5.91936814e-16+0.j        , -1.11022302e-16+1.31132345j,
       -1.11022302e-16-1.31132345j]), array([[ 0.21645083+0.32087282j,  0.21645083-0.32087282j,
        -0.61538462+0.j        , -0.400198  -0.02611738j,
        -0.400198  +0.02611738j],
       [ 0.14800892+0.35763625j,  0.14800892-0.35763625j,
         0.61538462+0.j        , -0.08070156-0.39284579j,
        -0.08070156+0.39284579j],
       [-0.03755848+0.40175237j, -0.03755848-0.40175237j,
        -0.30769231+0.j        ,  0.53837451+0.j        ,
         0.53837451-0.j        ],
       [-0.32690127+0.3282255j , -0.32690127-0.3282255j ,
         0.30769231+0.j        , -0.17981165+0.45357918j,
        -0.17981165-0.45357918j],
       [-0.56830214+0.j        , -0.56830214-0.j        ,
        -0.23076923+0.j        , -0.10559104-0.37317019j,
        -0.10559104+0.37317019j]]))


In [52]:
perm = np.argsort(np.abs(np.imag(u)))
print(perm)
unew = 1j*np.imag(u[perm])
print(unew)
vnew = v[perm,:]
print(vnew)
numblocks = np.flatnonzero(unew).size // 2
print(numblocks)
num_zeros = 5 - (2 * numblocks)
print(num_zeros)

[2 3 4 0 1]
[ 0.+0.j          0.+1.31132345j -0.-1.31132345j  0.+9.91364871j
 -0.-9.91364871j]
[[-0.03755848+0.40175237j -0.03755848-0.40175237j -0.30769231+0.j
   0.53837451+0.j          0.53837451-0.j        ]
 [-0.32690127+0.3282255j  -0.32690127-0.3282255j   0.30769231+0.j
  -0.17981165+0.45357918j -0.17981165-0.45357918j]
 [-0.56830214+0.j         -0.56830214-0.j         -0.23076923+0.j
  -0.10559104-0.37317019j -0.10559104+0.37317019j]
 [ 0.21645083+0.32087282j  0.21645083-0.32087282j -0.61538462+0.j
  -0.400198  -0.02611738j -0.400198  +0.02611738j]
 [ 0.14800892+0.35763625j  0.14800892-0.35763625j  0.61538462+0.j
  -0.08070156-0.39284579j -0.08070156+0.39284579j]]
2
1


In [53]:
from scipy.linalg import block_diag
T = la.block_diag(*[1.]*num_zeros, np.kron(1/np.sqrt(2)*np.eye(numblocks), np.array([[1.,1j],[1,-1j]])))
print(T)

[[1.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.70710678+0.j         0.        +0.70710678j
  0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.70710678+0.j         0.        -0.70710678j
  0.        +0.j         0.        -0.j        ]
 [0.        +0.j         0.        +0.j         0.        +0.j
  0.70710678+0.j         0.        +0.70710678j]
 [0.        +0.j         0.        +0.j         0.        -0.j
  0.70710678+0.j         0.        -0.70710678j]]


In [54]:
#print(*[1.]*num_zeros)
print(np.eye(numblocks)*1/np.sqrt(2))
print(np.array([[1.,1j],[1,-1j]]))
print(np.kron(np.eye(numblocks)*1/np.sqrt(2), np.array([[1.,1j],[1,-1j]])))

[[0.70710678 0.        ]
 [0.         0.70710678]]
[[ 1.+0.j  0.+1.j]
 [ 1.+0.j -0.-1.j]]
[[0.70710678+0.j         0.        +0.70710678j 0.        +0.j
  0.        +0.j        ]
 [0.70710678+0.j         0.        -0.70710678j 0.        +0.j
  0.        -0.j        ]
 [0.        +0.j         0.        +0.j         0.70710678+0.j
  0.        +0.70710678j]
 [0.        +0.j         0.        -0.j         0.70710678+0.j
  0.        -0.70710678j]]


In [55]:
Eigs = np.real(T.conj().T.dot(np.diag(unew).dot(T)))
print(Eigs)

[[ 0.          0.          0.          0.          0.        ]
 [ 0.          0.         -1.31132345  0.          0.        ]
 [ 0.          1.31132345  0.          0.         -0.        ]
 [ 0.          0.          0.          0.         -9.91364871]
 [ 0.          0.          0.          9.91364871  0.        ]]


In [56]:
Evecs = np.real(vnew.dot(T))
print(Evecs)

[[-0.03755848 -0.24412918  0.28408182  0.76137654  0.        ]
 [-0.32690127 -0.01358278  0.23209048 -0.25429208 -0.64145783]
 [-0.56830214 -0.56502878  0.         -0.14932828  0.52774235]
 [ 0.21645083 -0.28208878  0.22689135 -0.56596544  0.03693556]
 [ 0.14800892  0.53980075  0.25288702 -0.11412924  0.55556785]]


In [ ]:
# import numpy as np
# import scipy.linalg as la

# a=np.array([[0,-1,5,-3], [1,0,0,-1], [0,0,3,2], [0,0,5,-3]])
#a=a-np.transpose(a)

# print(a)

# #eigenvalue
# w, v =np.linalg.eig(a)
# print(w)
# print(v)

# #Schur decomposition
# import scipy
# print(scipy.version.version)

# t,z=la.schur(a, output='real', lwork=None, overwrite_a=True, sort=None, check_finite=True)

# print("schur form ")
# print(t)
# print("orthogonal matrix ")
# print(z)

S^t=(Q^tAQ)^t \
S^t=Q^t(Q^tA)^t \
S^t=Q^tA^tQ \
S^t=Q^t(-A)Q \
S^t=-Q^tAQ \
S^t=-S 